### ISSUE TITLE
New exercise save button not functional

### ISSUE THREAD

**Issue by ivandir** [wger-project/wger#505] opened 2020-08-29 16:37 UTC
When I try to create a new exercise and click the save button nothing is happening. This was just tested with the latest commit.
<img width="702" alt="Screen Shot 2020-08-29 at 12 36 40 PM" src="https://user-images.githubusercontent.com/2365911/91641725-6e4c2f00-e9f4-11ea-949f-62b0c0ca25ed.png">

**Comment by ivandir** [comment] 2020-08-29 16:39
Above capability was tested in a docker container that was run with

`docker run -ti --rm --name wger.devel --publish 8000:8000 wger/devel`

**Comment by rolandgeider** [comment] 2020-08-30 17:47
Thanks for reporting this, the issue is fixed in master

**Closed** 2020-08-30 17:46 UTC

**Comment by ivandir** [comment] 2020-08-31 14:56
Awesome thanks @rolandgeider I'll test it later today.
