### ISSUE TITLE
Weight Graph is inverted, old data cannot be deleted, graph shows weight > 100kg as 0

### ISSUE THREAD

**Issue by rklasen** [wger-project/wger#714] opened 2021-06-30 19:12 UTC
## Steps to Reproduce

First, thank you for this great program, and sorry if I'm submitting multiple issues / user errors at once.

1. I've sync'ed my weight from OpenScale with OpenScaleSync (seems to have worked, recent data is plausible)
2. But: apparently, the weight from anywhere in 2015 to 2016 was either invalid (NaN?) or negative or something else
3. The weight graph appears to be inverted as a result

I have no conclusive evidence that old weight data is actually invalid, it just seemed the most likely explanation. As a result, I would like to delete all entries from before ~2019

**Expected results:** 

I can only remove the individual entries shown below the graph, but not older entries nor date ranges

**Actual results:** 

When no date filter is applied, the weight graph is inverted (higher weight is downwards, lower weight is upwards). Hovering with the mouse over the graph shows NaN weight.

![image](https://user-images.githubusercontent.com/13201731/124017184-b823ee00-d9e6-11eb-8bb6-794f7521be5f.png)

When applying a filter for 12 months, the graph appears correct:

![image](https://user-images.githubusercontent.com/13201731/124017828-79426800-d9e7-11eb-8784-9e40554ef212.png)

But weight > 100 kg is shown 0 kg

**Software version**:

I'm using commit 72509a4f149584eb712336f2af1046ee458c1d17, hosted via docker-compose.

Thank you in advance!

<details>
  <summary>Logs</summary>

```
```

</details>

**Comment by rolandgeider** [comment] 2021-07-01 07:58
Thanks for the detailed bug report! This is indeed a strange behaviour, there shouldn't be anything done to the weight entries once they are in the DB, I'll try to reproduce this.

**Comment by rolandgeider** [comment] 2021-07-01 08:07
Can you check if the old data was imported correctly? You do this e.g. with the REST API http://your-host/api/v2/weightentry/?limit=1000

If everything is correct, this is only a bug in the chart

**Comment by rklasen** [comment] 2021-07-01 10:02
Thank you for the reply! I just tried it, the json is well-formatted and all weight entries are valid numbers, none of them are negative, zero or NaNs.

But I'm seeing something else which may cause errors: the IDs are not in the right order wrt to the date.

`tail -n 20 weight.json `:

```
{
            "id": 6,
            "date": "2021-06-07",
            "weight": "96.25",
            "user": 1
        },
        {
            "id": 3,
            "date": "2021-06-14",
            "weight": "96.15",
            "user": 1
        },
        {
            "id": 4,
            "date": "2021-06-21",
            "weight": "96.10",
            "user": 1
        },
        {
            "id": 2,
            "date": "2021-06-25",
            "weight": "95.85",
            "user": 1
        },
        {
            "id": 1,
            "date": "2021-06-30",
            "weight": "95.40",
            "user": 1
        },
        {
            "id": 312,
            "date": "2021-07-01",
            "weight": "95.55",
            "user": 1
        }
    ]
}
```

They are not in reverse either, but almost. It seems OpenScaleSync transferred them from most recent to oldest, but some entries still get switched. The very last entry with "id": 312 is from today, which also got sync'ed by OpenScaleSync, but a day after the others.

If it helps you, I can send you my json file.

**Comment by rolandgeider** [comment] 2021-07-01 10:08
The IDs shouldn't matter, the entries can be sorted by date. If I don't find anything with the chart logic, I'll come back to you about the json file

**Comment by rklasen** [comment] 2021-07-01 10:13
Hm, you're right, if the IDs were the problem, then today's graph with 12 month filter wouldn't work correctly either. I just quick'n'dirtyd the average weight over all entries, just to be sure, but all entries can be parsed to a python float correctly.

I didn't find any, but maybe there are multiple entries for the same date. Sometimes I took two or three measurements the same day and have OpenScale average them.

**Comment by rklasen** [comment] 2021-07-01 10:17
I'm so very sorry, the graph in the first image isn't inverted at all. I've just gained weight during the pandemic and was confused by the 00 above the 90 :facepalm: :facepalm: :facepalm: 

Soooo.... the only problems are now weight's > 100 being shown as 0, and the NaNs.

**Comment by rolandgeider** [comment] 2021-07-01 10:29
😂😂

One problem done, two to go

**Comment by rolandgeider** [comment] 2021-07-13 14:30
Just to let you know, I've started moving the weight part of the app to angular (since it's the simplest), once that's done those bugs will be gone

**Comment by rolandgeider** [comment] 2021-08-18 16:02
The angular UI is now available, closing here

**Closed by rolandgeider** 2021-08-18 16:02 UTC
Labels: type: bug

**Comment by rklasen** [comment] 2021-08-18 16:33
Fantastic, thank you. I will test it and open a new issue if the bug persists. But I doubt it. Thank you again for all your effort.
