### ISSUE TITLE
Unable to delete weight entries

### ISSUE THREAD

**Issue by Captain-Rage** [wger-project/wger#430] opened 2018-05-23 23:03 UTC
Hi,
I just registered an account at https://wger.de. While looking like a very sophisticated piece of software, I immediately ran into trouble:

'Weight' → 'Add weight entry' → 'Weight': 600 kg

Now it shows up under 'Weight' → 'Weight overview' without any option to remove said entry. How can I delete added weight entries?

**Comment by Captain-Rage** [comment] 2018-05-23 23:12
Apparently this is old issue. However, in another ticket it was written that you can atleast edit old entries but I don't see how. How can you change the value of an old weight entry?

**Comment by rolandgeider** [comment] 2020-08-26 18:24
Sorry for the late reply, the project is active again. I'm marking this a duplicate of #478 and closing here

**Closed by rolandgeider** 2020-08-26 18:24 UTC
