### ISSUE TITLE
Edit Exercise function seems to have issues

### ISSUE THREAD

**Issue by kris-gs** [wger-project/wger#1840] opened 2024-12-11 06:27 UTC
## Steps to Reproduce

https://wger-master.rge.uber.space/en/user/login

1. Login with admin privileges 
2. Training > exercises > 'select any exercise' > click 'edit'

![Image](https://github.com/user-attachments/assets/b34a628c-d666-4e7a-b052-e03356591b44)

**Expected results:** 

Edit page with the ability to edit the exercise

**Actual results:** 

Blank page

![Image](https://github.com/user-attachments/assets/95f5bfc5-fc4a-467c-ae1c-beeae2c5c3ed)

</details>

**Comment by rolandgeider** [comment] 2024-12-12 19:39
hi! this is probably a duplicate of #1742, should be fixed now

**Closed by rolandgeider** 2024-12-12 19:39 UTC
