### ISSUE TITLE
Set video to main video in edit screen throws: 'File' object has no attribute 'content_type'

### ISSUE THREAD

**Issue by DunklerPhoenix** [wger-project/wger#1017] opened 2022-04-15 19:48 UTC
## Steps to Reproduce

1. Upload a video without setting it as main video
2. Edit the uploaded video
3. set it as main video
4. get this error message

whole error message in html:
[AttributeError at _de_exercise_video_677_1_edit.html.txt](https://github.com/wger-project/wger/files/8497979/AttributeError.at._de_exercise_video_677_1_edit.html.txt)

PS: Aren't this too much sensible informations for a productivity error page?

EDIT: I don't choose an video for replacing the old one.

**Comment by rolandgeider** [comment] 2022-11-30 13:35
Videos are now uploaded via the API closing here since I couldn't reproduce it anymore (but obviously just open a new issue if it happens again)

**Closed by rolandgeider** 2022-11-30 13:35 UTC
Labels: type: bug
