### ISSUE TITLE
Exercises

### ISSUE THREAD

**Issue by illegalnumbers** [wger-project/wger#338] opened 2016-10-01 22:14 UTC
Have you seen this? 

http://www.exrx.net/Lists/WorkoutMenu.html

Seems like a lot of really good information there. Wasn't sure if you had seen it previously or if you had used anything similar to get workout information before. There are many other resources available out there and there might not be a license on that site for usage, but hopefully there is!

**Comment by rolandgeider** [comment] 2016-10-01 22:41
Yeah, I've seen it, the problem is the licence as you mention. I had looked around but could not find any database that can be freely used, but perhaps something has cropped out in the meantime. I'm however not very hopeful because what we are looking for here is rather a niche combination :)

**Comment by 12people** [comment] 2019-12-26 19:09
@rolandgeider Perhaps close this issue, given that exrx isn't freely licensed?

**Closed** 2020-12-03 14:38 UTC
