### ISSUE TITLE
Make the app work offline

### ISSUE THREAD

**Issue by foss-enjoyer** [wger-project/wger#1464] opened 2023-10-16 19:21 UTC
## Use case
The android app is useless without the internet. The app would be better if we could access our workout plans offline.

## Proposal
Make the app functional the without internet. Sync new data when the internet is available.

**Comment by rolandgeider** [comment] 2023-10-17 11:15
Fun fact, adding an offline mode is one of the first issues we opened for the app https://github.com/wger-project/flutter/issues/6. The problem is that this will be a lot of work, but we will definitely try to at least add this to the gym mode, one day 

(closing here, but open further issues if you find anything that's missing)

**Closed by rolandgeider** 2023-10-17 11:15 UTC
