### ISSUE TITLE
Dashboard should be able to customize to show weights you have lifted

### ISSUE THREAD

**Issue by illegalnumbers** [wger-project/wger#351] opened 2016-11-26 02:01 UTC
One thing I really liked about the 5x5 app I was using was that it showed me that yes, I was getting stronger - just look at the data! It seems you have the log functionality installed in some places but it is hard to get to - it should be very easy to add your workouts and see them on the dashboard and see how far back you want to see historically.

**Comment by illegalnumbers** [comment] 2016-11-26 02:04
It should also as a part of this be easy to log exercises you've done - it seems that functionality is hard to get to as well. Your plan might be to hit 5x5 for a workout but maybe you hit 4x5 and then 3x4 or something - it would be good to see where you stack up.

**Comment by rolandgeider** [comment] 2016-11-30 13:35
Duplicate of #201, closing here

**Closed by rolandgeider** 2016-11-30 13:35 UTC
