### ISSUE TITLE
Getting a "404 Page Not Found" error after attempting to save a workout on mobile - 'null' username?

### ISSUE THREAD

**Issue by dohlin** [wger-project/wger#404] opened 2017-07-26 19:58 UTC
Hey guys,

Hoping someone can assist me here...I followed the steps to install Wger from git, and most everything (so far) seemed to be working great.  However, today when trying to use it for the first time after I had created some daily workouts with excercises, I get to the end of it and click the final "save" button and am then greeted with a "Page not found (404)" error.  It says the following:

Request Method: GET
Request URL: http://[example.com]/en/workout/calendar/null/2017/7/26
Raised by: wger.manager.views.log.day

No User matches the given query.

You're seeing this error because you have DEBUG = True in your Django settings file.  Change that to False, and Django will display a standard 404 page.

Any thoughts here?  Oddly enough it does seem to save the workout, but the issue I'm seeing is the "null" part...however I'm not sure why that's there and I've tried deleted and re-registering a user but the issue still persists.  Any advice would be greatly appreciated.  Thanks!

EDIT:  So thinking maybe I just screwed something up I just tried fully wiping and reloading with a fresh copy of Ubuntu 16.04, and following the git install directions, and immediately after a fresh install using the default admin/admin creds I get the same error.  I'm convinced it's got something to do with the "null" that's in the URL noted, but again I'm just not sure why or where that's getting pulled from.  For what it's worth, the last few lines of the console log show the following:

[26/Jul/2017 16:44:21] "POST /en/user/login HTTP/1.1" 302 0
[26/Jul/2017 16:44:21] "GET / HTTP/1.1" 302 0
[26/Jul/2017 16:44:21] "GET /en/ HTTP/1.1" 302 0
[26/Jul/2017 16:44:21] "GET /en/dashboard HTTP/1.1" 200 41406
[26/Jul/2017 16:44:25] "GET /en/workout/1/timer HTTP/1.1" 200 53681
[26/Jul/2017 16:44:28] "POST /api/v2/workoutlog/ HTTP/1.1" 400 42
[26/Jul/2017 16:44:29] "POST /en/workout/session/1/add/2017-7-26 HTTP/1.1" 302 0
[26/Jul/2017 16:44:30] "GET /en/workout/calendar HTTP/1.1" 200 41849
[26/Jul/2017 16:44:30] "GET /api/v2/userprofile/ HTTP/1.1" 200 546
Not Found: /api/v2/userprofile/null/username/
[26/Jul/2017 16:44:30] "GET /api/v2/userprofile/null/username/ HTTP/1.1" 404 23
Not Found: /en/workout/calendar/null/2017/7/26
[26/Jul/2017 16:44:31] "GET /en/workout/calendar/null/2017/7/26 HTTP/1.1" 404 1775
Not Found: /favicon.ico
[26/Jul/2017 16:44:31] "GET /favicon.ico HTTP/1.1" 404 3098

Thanks!

**Comment by dohlin** [comment] 2017-08-04 19:25
Is no one else seeing this issue?  Happens when using my smartphone and directly accessing the site I have this running at.

**Comment by DandyDeveloper** [comment] 2017-09-25 21:31
Just looking at the surface of this, is this because the admin account isn't truly connected throughout the app? What if you register another account and try this using that account? 

I'll see if I can look into this - Unless you made progress?

**Comment by dohlin** [comment] 2017-09-25 22:04
I haven't made any progress, no.  Given that the error kinda made things not very usable since it happened every workout, I ended up just shutting the server down and haven't used it since.  I still have the VM so I could potentially power it back up and test, but I found a similar app that does the same basic thing so I don't know if it's worth the hassle at the point...if no one else is seeing this then probably ok to just go ahead and close.  Thanks!!

**Comment by DandyDeveloper** [comment] 2017-09-26 05:59
@dohlin I've checked with the owner of the repo they are actually looking at PRs, if they are, I can definitely look into this.

**Comment by dohlin** [comment] 2017-09-26 11:06
@dandydeveloper ok, sounds good!  Thanks!

**Comment by dohlin** [comment] 2017-09-28 04:48
@DandyDeveloper Update - I fired everything back up, and even went back through the production steps here from scratch just to be certain I had everything current and up to date:

https://wger.readthedocs.io/en/latest/production.html#application

Afterwards I created a django super admin, tried my original issue test with that and got the exact same error.

Then I created a 2nd user (just via the Wger gui like normal) and did the exact same thing (created a workout, started it, went through it, and hit save at the end)...again exact same issue.  So no, it doesn't appear to be related to just the "admin" user.

Also, I'm getting the following error log when I log in as the django super admin, go to the users list, choose my "normal" (2nd) user I created, and choose "log in as this user", and then choose the "Back to """ button:

Internal Server Error: /en/user/3/trainer-login

NoReverseMatch at /en/user/3/trainer-login
Reverse for 'user-list' with arguments '()' and keyword arguments '{'pk': None}' not found. 1 pattern(s) tried: ['en/gym/(?P<pk>\\d+)/members$']

I get a big huge long email with the above and a bunch more dev-type info.

**Comment by DandyDeveloper** [comment] 2017-09-28 05:40
Hey Dohlin, the second error is a knock on from the first as the url its using is basically from a non-existent user in the database. Its the knock on effect of the bug you've found. 

I'm still wanting to look into this, but I'm waiting until the maintainers confirm they are actually still trying to keep this project live. Otherwise my changes would be for nothing!

**Comment by dohlin** [comment] 2017-09-28 05:45
@dandydeveloper gotcha, that makes sense.  I went ahead and just shut that VM back down for now so I'll just await any potential updates one way or another.  Thanks again!

**Comment by rolandgeider** [comment] 2017-10-06 17:40
Hi there! I'm one of the maintainers that @DandyDeveloper mentioned, I have indeed left the project a bit in the rain for far too long, but want to get everything running again and have now a really long backlog of things I need to do and issues I need to answer!

**Comment by dohlin** [comment] 2017-10-06 17:47
@rolandgeider ok great!  I'll hold off on deleting my virtual machine for a while longer and await further developments haha :)

**Comment by DandyDeveloper** [comment] 2017-10-06 18:44
@rolandgeider If you need contributors, I'd be more then willing to help out with things. Let me know if I can make a start on the PRs based on the issues raised.

**Comment by rolandgeider** [comment] 2017-10-07 11:03
Gladly! I've added you to the developer team

**Comment by DandyDeveloper** [comment] 2017-10-07 19:14
Okay so I've tried reproducing this using a blank database and I'm having no success. Sorry to be a pain with this, but could you give me a step by step on how you reproduced? It might be specific to the steps you've taken.

**Comment by dohlin** [comment] 2017-10-07 21:12
It's been so long I don't even think I could give you an exact synopsis honestly...I believe the first time or two I followed the dev or pypi setup instructions in the readme, and most recently I followed the main instructions for setup at https://wger.readthedocs.io/en/latest/production.html.  After that I created a Django super admin I believe so that I could log in to the admin portal and rename the site, etc.  Then logging in with that same account (or a different one) on my mobile device I create a new workout with just a single workout or two...then I start it, finish it, and on the final save page after clicking the save button it errors out.  I don't know if it'd be possible for me to provide any other logs somehow?  

I'm not a complete noob, but compared to you guys I very much am so if you can spell it out pretty noob proof I'd be happy to try to help find the error.  I would totally think that maybe I just configured something wrong or something, but the thing is I've now installed it 2 or 3 times and ran into the issue each is odd to me.

**Comment by DandyDeveloper** [comment] 2017-10-09 14:57
Super admin? Hmm, normally the initialisation instructions should include a bunch of fixtures that insert the accounts (User: admin / Pass: admin). I'll try it using that method. Thanks for the update Dohlin.

**Comment by dohlin** [comment] 2017-10-09 15:05
@dandydeveloper yes I started by using the admin/admin but iirc that didn't allow me to log into the django admin portal to change the site name so that emails sent reflect the site URL correctly...so I had to create the super admin eventually regardless as far as I understood.  It encountered the error with both accounts though.

I should note though that I know I would have changed both the username and password of the initially admin/admin account (you know, security through obscurity of sorts lol)...so you could try changing the normal admin/admin username to an email address or something and changing the password and see if it happens then.

**Comment by DandyDeveloper** [comment] 2017-10-09 19:53
Yeah I'm struggling a heap to reproduce this. Can you just zip up your entire wger folder and send it to me?

**Comment by dohlin** [comment] 2017-10-09 20:34
@dandydeveloper Definitely!  Do you want me to do anything special like reproducing it right before or anything?  Or just power up the VM (it's powered down rn), zip the folder, and send?

**Comment by rolandgeider** [comment] 2017-10-10 07:33
The admin interface might require an actual super user, but the default 
admin user generated via the fixtures is just a regular user that 
happens to have all the edit and delete permissions. Try to log into 
your DB and set "is_staff" to true on the django_auth table and see if 
you can get in

Am 09.10.2017 um 22:34 schrieb dohlin:

**Comment by dohlin** [comment] 2017-10-10 12:00
Yeah I guess I just figured I'd change the default admin username because there's a part of me that hates having just 'admin' as a username anywhere :)

But like I said I had the same issue regardless of whether that account or another one was used.

@DandyDeveloper I've zipped up both my wger folder as well as my wger virtualenv folder in case you want to look at that too.  Sending links to your Gmail now.  I'd love nothing more than for you to tell me I simply have something misconfugred lol :)

Also, for what it's worth - I had just been starting the server with a script that ran on boot that ran the following command:

python manage.py runserver --insecure 0.0.0.0:8000

I did this because for some reason I was having trouble getting Apache to properly serve image & resource files whenever I'd change debug = false instead of true.  I troubleshooted it for a while but once I realize the above worked I just ran with it.

**Comment by DandyDeveloper** [comment] 2017-10-11 20:44
Okay, I've been able to reproduce this on mobile. I will investigate further.

**Comment by DandyDeveloper** [comment] 2017-10-12 21:02
@rolandgeider I've looked into this and the problem is definitely due to: 

`[12/Oct/2017 21:57:49] "POST /en/workout/session/4/edit HTTP/1.1" 302 0` (workout_session.py -> WorkoutSessionUpdateView -> get_success_url) 

Resulting in the following being loaded: 

`[12/Oct/2017 21:57:49] "GET /en/workout/calendar HTTP/1.1" 200 177575`
`[12/Oct/2017 21:57:50] "GET /api/v2/userprofile/ HTTP/1.1" 200 547`

What I can't work out is why it's loading the `/api/v2/userprofile/` page. Any help?

**Comment by rolandgeider** [comment] 2017-10-17 17:24
Mhhh, it might be trying to load something from the userprofile, but I can't tell you what. I'll take a look. It's also interesting that this seems to happen only on the mobile version

**Comment by Drudoo** [comment] 2018-04-11 15:53
I am getting the exact same issue. Really demotivating when trying to use this as my main workout manager.

**Comment by rolandgeider** [comment] 2020-10-08 14:45
The mobile version was more or less completly rewritten in the meantime, closing here

**Closed by rolandgeider** 2020-10-08 14:45 UTC
